### ISSUE TITLE
Support for Sublime 3

### ISSUE THREAD

**Issue by dimitarkolev** [TurtlePie/Sublime-ECT#1]
Can make it compatible with Sublime 3?

**Comment by nfour** [comment]
What's the problem? I'm using build 3083 and all is well.

**Comment by dimitarkolev** [comment]
Cant find it in package manager.

**Comment by nfour** [comment]
If you cant find it then just git clone/save this repo into the folder `/Sublime Text 3/Data/Packages/ECT`

**Comment by dimitarkolev** [comment]
10x
